### ISSUE TITLE
Unable to stop frida-server

### ISSUE THREAD

**Issue by shivampayzeb2** [Hamz-a/frida-android-helper#5] opened 2022-05-19 10:19 UTC
Hi, Frida service seems to be running after executing ```python3 fah.py server stop``` command.  Also not sure where is the frida-server binary stored in android.

**Comment by Hamz-a** [comment] 2022-05-20 07:13
@shivampayzeb2 hey there! Can you `adb shell` into your device, elevate privileges and run `pkill frida-server`? Because that is basically what the script is doing. If you installed `frida-server` through FAH, then you should be able to find the binary in `/data/local/tmp/`.

**Comment by shivampayzeb2** [comment] 2022-05-20 10:02
@Hamz-a I tried with ```pkill frida-server``` but return value is 1. I even tried to grep frida in the running process but doesn't show the process with name frida.  ```ps -A | grep frida``` but strangely the device shows up with ```frida-ls-devices ```
Even when I reboot my device, frida server seems to be running
Frida Version: 15.1.22

**Comment by Hamz-a** [comment] 2022-05-20 10:31
@shivampayzeb2 if `pkill` returns `1`, it means it could not find a match. I ran `frida-ls-devices` with a non-rooted device (meaning no Frida installed) and it still showed the device. Did you perhaps use an obfuscated version of Frida where the frida binary is different? Can you `ls /data/local/tmp/`?

**Comment by shivampayzeb2** [comment] 2022-05-20 11:08
Files in ```/data/local/tmp```
```35aa2e12  frida-server```
Apart from frida-ls-devices, ```frida-ps -Ua ``` also shows the running application on a reboot
<img width="627" alt="image" src="https://user-images.githubusercontent.com/77335313/169515497-f254abd3-00c2-48e3-84e4-bf6df49bdbae.png">
 I'm not sure how to kill the frida service!

**Comment by Hamz-a** [comment] 2022-05-20 11:11
@shivampayzeb2 how did you install frida-server and/or which tutorial did you follow?

**Comment by shivampayzeb2** [comment] 2022-05-20 11:14
@Hamz-a After I installed magisk, I used fah utility itself to install frida 
```python3 fah.py server start```

**Comment by Hamz-a** [comment] 2022-05-20 11:39
@shivampayzeb2 I'm guessing that `frida-server`  is not running then. Can u `adb shell` and run the following command `netstat -a | grep 27042`? If you do not have any output, then most probably `frida-server` is not running...

**Comment by shivampayzeb2** [comment] 2022-05-20 12:35
Yes! This is very strange behavior of ```frida-ps -Ua``` and ```frida-ls-devices``` responding without frida-server running.

**Comment by Hamz-a** [comment] 2022-05-22 22:20
@shivampayzeb2 is it fine if I close this issue as the problem is not FAH related?

**Closed** 2022-05-27 23:27 UTC
